# LikesAddon Configuration 2.0.0
# This config file is dynamic and saved when the server is shutdown.
#
#
# Default icon for Top Island panel.
# Should be valid Material
default-icon: PLAYER_HEAD
#
# Allows to enable ability to send message to island members about someone
# liking or disliking their island.
inform-members: true
#
# Allows to switch addon between 3 different modes:
#   - LIKES: allows only adding a like to island.
#   - LIKES_DISLIKES: allows only adding a like and dislike to island.
#   - STARS: allows adding stars from 1-5 to island.
mode: LIKES_DISLIKES
costs:
  #
  # Allows to define cost for player to add like.
  add-like: 0.0
  #
  # Allows to define cost for player to remove like.
  remove-like: 0.0
  #
  # Allows to define cost for player to add dislike.
  add-dislike: 0.0
  #
  # Allows to define cost for player to remove dislike.
  remove-dislike: 0.0
#
# Allows reset likes and dislikes after resetting island.
reset-on-reset: true
#
# Allows to store history data about added and removed likes and dislikes.
log-history: false
#
# Allows adding likes/dislikes or stars to the unowned islands. This includes spawn island.
allow-unowned: true
#
# This list stores GameModes in which Likes addon should not work.
# To disable addon it is necessary to write its name in new line that starts with -. Example:
# disabled-gamemodes:
#  - BSkyBlock
disabled-gamemodes: []